/*
 * This file is generated by jOOQ.
 */
package org.dazai.booksourcing.main.domain.db.tables.records;


import java.time.Instant;

import org.dazai.booksourcing.main.domain.db.tables.ExchangeRequest;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExchangeRequestRecord extends UpdatableRecordImpl<ExchangeRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.owner_id</code>.
     */
    public void setOwnerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.owner_book_id</code>.
     */
    public void setOwnerBookId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.owner_book_id</code>.
     */
    public Long getOwnerBookId() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>DEFAULT_SCHEMA.exchange_request.requestor_book_id</code>.
     */
    public void setRequestorBookId(Long value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>DEFAULT_SCHEMA.exchange_request.requestor_book_id</code>.
     */
    public Long getRequestorBookId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.requestor_id</code>.
     */
    public void setRequestorId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.requestor_id</code>.
     */
    public Long getRequestorId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.request_date</code>.
     */
    public void setRequestDate(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.request_date</code>.
     */
    public Instant getRequestDate() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.response_date</code>.
     */
    public void setResponseDate(Instant value) {
        set(7, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.response_date</code>.
     */
    public Instant getResponseDate() {
        return (Instant) get(7);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.completion_date</code>.
     */
    public void setCompletionDate(Instant value) {
        set(8, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.completion_date</code>.
     */
    public Instant getCompletionDate() {
        return (Instant) get(8);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.from_publication</code>.
     */
    public void setFromPublication(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.from_publication</code>.
     */
    public Long getFromPublication() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.message</code>.
     */
    public void setMessage(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.message</code>.
     */
    public String getMessage() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExchangeRequestRecord
     */
    public ExchangeRequestRecord() {
        super(ExchangeRequest.EXCHANGE_REQUEST);
    }

    /**
     * Create a detached, initialised ExchangeRequestRecord
     */
    public ExchangeRequestRecord(Long id, Long ownerId, Long ownerBookId, Long requestorBookId, Long requestorId, String status, Instant requestDate, Instant responseDate, Instant completionDate, Long fromPublication, String message) {
        super(ExchangeRequest.EXCHANGE_REQUEST);

        setId(id);
        setOwnerId(ownerId);
        setOwnerBookId(ownerBookId);
        setRequestorBookId(requestorBookId);
        setRequestorId(requestorId);
        setStatus(status);
        setRequestDate(requestDate);
        setResponseDate(responseDate);
        setCompletionDate(completionDate);
        setFromPublication(fromPublication);
        setMessage(message);
        resetChangedOnNotNull();
    }
}
