/*
 * This file is generated by jOOQ.
 */
package org.dazai.booksourcing.main.domain.db.tables.records;


import java.time.Instant;

import org.dazai.booksourcing.main.domain.db.tables.ExchangeRequest;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExchangeRequestRecord extends UpdatableRecordImpl<ExchangeRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for
     * <code>DEFAULT_SCHEMA.exchange_request.requested_book_id</code>.
     */
    public void setRequestedBookId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>DEFAULT_SCHEMA.exchange_request.requested_book_id</code>.
     */
    public ULong getRequestedBookId() {
        return (ULong) get(1);
    }

    /**
     * Setter for
     * <code>DEFAULT_SCHEMA.exchange_request.requestor_book_id</code>.
     */
    public void setRequestorBookId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>DEFAULT_SCHEMA.exchange_request.requestor_book_id</code>.
     */
    public ULong getRequestorBookId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.requestor_id</code>.
     */
    public void setRequestorId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.requestor_id</code>.
     */
    public ULong getRequestorId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.owner_id</code>.
     */
    public void setOwnerId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.owner_id</code>.
     */
    public ULong getOwnerId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.request_date</code>.
     */
    public void setRequestDate(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.request_date</code>.
     */
    public Instant getRequestDate() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.response_date</code>.
     */
    public void setResponseDate(Instant value) {
        set(7, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.response_date</code>.
     */
    public Instant getResponseDate() {
        return (Instant) get(7);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.completion_date</code>.
     */
    public void setCompletionDate(Instant value) {
        set(8, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.completion_date</code>.
     */
    public Instant getCompletionDate() {
        return (Instant) get(8);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.exchange_request.message</code>.
     */
    public void setMessage(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.exchange_request.message</code>.
     */
    public String getMessage() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExchangeRequestRecord
     */
    public ExchangeRequestRecord() {
        super(ExchangeRequest.EXCHANGE_REQUEST);
    }

    /**
     * Create a detached, initialised ExchangeRequestRecord
     */
    public ExchangeRequestRecord(ULong id, ULong requestedBookId, ULong requestorBookId, ULong requestorId, ULong ownerId, String status, Instant requestDate, Instant responseDate, Instant completionDate, String message) {
        super(ExchangeRequest.EXCHANGE_REQUEST);

        setId(id);
        setRequestedBookId(requestedBookId);
        setRequestorBookId(requestorBookId);
        setRequestorId(requestorId);
        setOwnerId(ownerId);
        setStatus(status);
        setRequestDate(requestDate);
        setResponseDate(responseDate);
        setCompletionDate(completionDate);
        setMessage(message);
        resetChangedOnNotNull();
    }
}
