/*
 * This file is generated by jOOQ.
 */
package org.dazai.booksourcing.main.domain.db.tables.records;


import java.time.Instant;

import org.dazai.booksourcing.main.domain.db.tables.Publication;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PublicationRecord extends UpdatableRecordImpl<PublicationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DEFAULT_SCHEMA.publication.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.publication.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.publication.offered_book_id</code>.
     */
    public void setOfferedBookId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.publication.offered_book_id</code>.
     */
    public ULong getOfferedBookId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.publication.owner_id</code>.
     */
    public void setOwnerId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.publication.owner_id</code>.
     */
    public ULong getOwnerId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.publication.offer_details</code>.
     */
    public void setOfferDetails(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.publication.offer_details</code>.
     */
    public String getOfferDetails() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.publication.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.publication.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.publication.created_date</code>.
     */
    public void setCreatedDate(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.publication.created_date</code>.
     */
    public Instant getCreatedDate() {
        return (Instant) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PublicationRecord
     */
    public PublicationRecord() {
        super(Publication.PUBLICATION);
    }

    /**
     * Create a detached, initialised PublicationRecord
     */
    public PublicationRecord(ULong id, ULong offeredBookId, ULong ownerId, String offerDetails, String status, Instant createdDate) {
        super(Publication.PUBLICATION);

        setId(id);
        setOfferedBookId(offeredBookId);
        setOwnerId(ownerId);
        setOfferDetails(offerDetails);
        setStatus(status);
        setCreatedDate(createdDate);
        resetChangedOnNotNull();
    }
}
