/*
 * This file is generated by jOOQ.
 */
package org.dazai.booksourcing.main.domain.db.tables.records;


import org.dazai.booksourcing.main.domain.db.tables.UserProfile;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserProfileRecord extends UpdatableRecordImpl<UserProfileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DEFAULT_SCHEMA.user_profile.bio</code>.
     */
    public void setBio(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.user_profile.bio</code>.
     */
    public String getBio() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.user_profile.id</code>.
     */
    public void setId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.user_profile.id</code>.
     */
    public ULong getId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.user_profile.user_id</code>.
     */
    public void setUserId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.user_profile.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.user_profile.first_name</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.user_profile.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.user_profile.last_name</code>.
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.user_profile.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.user_profile.address</code>.
     */
    public void setAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.user_profile.address</code>.
     */
    public String getAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.user_profile.phone</code>.
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.user_profile.phone</code>.
     */
    public String getPhone() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserProfileRecord
     */
    public UserProfileRecord() {
        super(UserProfile.USER_PROFILE);
    }

    /**
     * Create a detached, initialised UserProfileRecord
     */
    public UserProfileRecord(String bio, ULong id, ULong userId, String firstName, String lastName, String address, String phone) {
        super(UserProfile.USER_PROFILE);

        setBio(bio);
        setId(id);
        setUserId(userId);
        setFirstName(firstName);
        setLastName(lastName);
        setAddress(address);
        setPhone(phone);
        resetChangedOnNotNull();
    }
}
