FROM azul/zulu-openjdk:21 AS build

WORKDIR /app
COPY . .

RUN ./gradlew :auth:server:standalone:bootJar

FROM azul/zulu-openjdk:21-jre

WORKDIR /app

COPY --from=build /app/auth/server/standalone/build/libs/standalone-0.0.1-SNAPSHOT.jar /app/standalone.jar

ENTRYPOINT ["java", "-jar", "/app/standalone.jar"]