FROM azul/zulu-openjdk:21 AS build

WORKDIR /app
COPY . .

RUN ./gradlew :main:server:standalone:bootJar

FROM azul/zulu-openjdk:21

WORKDIR /app

COPY --from=build /app/main/server/standalone/build/libs/standalone-0.0.1-SNAPSHOT.jar /app/standalone.jar

#ENTRYPOINT ["java", "-XX:+UseZGC", "-Xmx4g", "-jar", "/app/standalone.jar"]