/*
 * This file is generated by jOOQ.
 */
package org.dazai.booksourcing.main.domain.db.tables;


import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.dazai.booksourcing.main.domain.db.DefaultSchema;
import org.dazai.booksourcing.main.domain.db.Indexes;
import org.dazai.booksourcing.main.domain.db.Keys;
import org.dazai.booksourcing.main.domain.db.tables.records.ExchangeRequestRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import tech.ydb.jooq.binding.TimestampBinding;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExchangeRequest extends TableImpl<ExchangeRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA.exchange_request</code>
     */
    public static final ExchangeRequest EXCHANGE_REQUEST = new ExchangeRequest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExchangeRequestRecord> getRecordType() {
        return ExchangeRequestRecord.class;
    }

    /**
     * The column <code>DEFAULT_SCHEMA.exchange_request.id</code>.
     */
    public final TableField<ExchangeRequestRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>DEFAULT_SCHEMA.exchange_request.requested_book_id</code>.
     */
    public final TableField<ExchangeRequestRecord, Long> REQUESTED_BOOK_ID = createField(DSL.name("requested_book_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>DEFAULT_SCHEMA.exchange_request.requestor_book_id</code>.
     */
    public final TableField<ExchangeRequestRecord, Long> REQUESTOR_BOOK_ID = createField(DSL.name("requestor_book_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DEFAULT_SCHEMA.exchange_request.requestor_id</code>.
     */
    public final TableField<ExchangeRequestRecord, Long> REQUESTOR_ID = createField(DSL.name("requestor_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DEFAULT_SCHEMA.exchange_request.owner_id</code>.
     */
    public final TableField<ExchangeRequestRecord, Long> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DEFAULT_SCHEMA.exchange_request.status</code>.
     */
    public final TableField<ExchangeRequestRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(4194304).nullable(false), this, "");

    /**
     * The column <code>DEFAULT_SCHEMA.exchange_request.request_date</code>.
     */
    public final TableField<ExchangeRequestRecord, Instant> REQUEST_DATE = createField(DSL.name("request_date"), SQLDataType.LOCALDATETIME(26).nullable(false), this, "", new TimestampBinding());

    /**
     * The column <code>DEFAULT_SCHEMA.exchange_request.response_date</code>.
     */
    public final TableField<ExchangeRequestRecord, Instant> RESPONSE_DATE = createField(DSL.name("response_date"), SQLDataType.LOCALDATETIME(26), this, "", new TimestampBinding());

    /**
     * The column <code>DEFAULT_SCHEMA.exchange_request.completion_date</code>.
     */
    public final TableField<ExchangeRequestRecord, Instant> COMPLETION_DATE = createField(DSL.name("completion_date"), SQLDataType.LOCALDATETIME(26), this, "", new TimestampBinding());

    /**
     * The column <code>DEFAULT_SCHEMA.exchange_request.from_publication</code>.
     */
    public final TableField<ExchangeRequestRecord, Long> FROM_PUBLICATION = createField(DSL.name("from_publication"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>DEFAULT_SCHEMA.exchange_request.message</code>.
     */
    public final TableField<ExchangeRequestRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.VARCHAR(4194304), this, "");

    private ExchangeRequest(Name alias, Table<ExchangeRequestRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ExchangeRequest(Name alias, Table<ExchangeRequestRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>DEFAULT_SCHEMA.exchange_request</code> table
     * reference
     */
    public ExchangeRequest(String alias) {
        this(DSL.name(alias), EXCHANGE_REQUEST);
    }

    /**
     * Create an aliased <code>DEFAULT_SCHEMA.exchange_request</code> table
     * reference
     */
    public ExchangeRequest(Name alias) {
        this(alias, EXCHANGE_REQUEST);
    }

    /**
     * Create a <code>DEFAULT_SCHEMA.exchange_request</code> table reference
     */
    public ExchangeRequest() {
        this(DSL.name("exchange_request"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.EXCHANGE_REQUEST__OWNER_ID__IDX, Indexes.EXCHANGE_REQUEST__REQUESTED_BOOK_ID__IDX, Indexes.EXCHANGE_REQUEST__REQUESTOR_BOOK_ID__IDX, Indexes.EXCHANGE_REQUEST__REQUESTOR_ID__IDX, Indexes.EXCHANGE_REQUEST__STATUS__IDX);
    }

    @Override
    public UniqueKey<ExchangeRequestRecord> getPrimaryKey() {
        return Keys.PK_EXCHANGE_REQUEST;
    }

    @Override
    public ExchangeRequest as(String alias) {
        return new ExchangeRequest(DSL.name(alias), this);
    }

    @Override
    public ExchangeRequest as(Name alias) {
        return new ExchangeRequest(alias, this);
    }

    @Override
    public ExchangeRequest as(Table<?> alias) {
        return new ExchangeRequest(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ExchangeRequest rename(String name) {
        return new ExchangeRequest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExchangeRequest rename(Name name) {
        return new ExchangeRequest(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExchangeRequest rename(Table<?> name) {
        return new ExchangeRequest(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExchangeRequest where(Condition condition) {
        return new ExchangeRequest(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExchangeRequest where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExchangeRequest where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExchangeRequest where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExchangeRequest where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExchangeRequest where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExchangeRequest where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExchangeRequest where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExchangeRequest whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExchangeRequest whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
