/*
 * This file is generated by jOOQ.
 */
package org.dazai.booksourcing.main.domain.db;


import org.dazai.booksourcing.main.domain.db.tables.Book;
import org.dazai.booksourcing.main.domain.db.tables.ExchangeRequest;
import org.dazai.booksourcing.main.domain.db.tables.FlywaySchemaHistory;
import org.dazai.booksourcing.main.domain.db.tables.Publication;
import org.dazai.booksourcing.main.domain.db.tables.UserProfile;


/**
 * Convenience access to all tables in DEFAULT_SCHEMA.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>DEFAULT_SCHEMA.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>DEFAULT_SCHEMA.exchange_request</code>.
     */
    public static final ExchangeRequest EXCHANGE_REQUEST = ExchangeRequest.EXCHANGE_REQUEST;

    /**
     * The table <code>DEFAULT_SCHEMA.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>DEFAULT_SCHEMA.publication</code>.
     */
    public static final Publication PUBLICATION = Publication.PUBLICATION;

    /**
     * The table <code>DEFAULT_SCHEMA.user_profile</code>.
     */
    public static final UserProfile USER_PROFILE = UserProfile.USER_PROFILE;
}
