/*
 * This file is generated by jOOQ.
 */
package org.dazai.booksourcing.auth.domain.db;


import java.util.Arrays;
import java.util.List;

import org.dazai.booksourcing.auth.domain.db.tables.FlywaySchemaHistory;
import org.dazai.booksourcing.auth.domain.db.tables.JwtTokens;
import org.dazai.booksourcing.auth.domain.db.tables.UserRoles;
import org.dazai.booksourcing.auth.domain.db.tables.Users;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>DEFAULT_SCHEMA.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>DEFAULT_SCHEMA.jwt_tokens</code>.
     */
    public final JwtTokens JWT_TOKENS = JwtTokens.JWT_TOKENS;

    /**
     * The table <code>DEFAULT_SCHEMA.user_roles</code>.
     */
    public final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>DEFAULT_SCHEMA.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("DEFAULT_SCHEMA", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            JwtTokens.JWT_TOKENS,
            UserRoles.USER_ROLES,
            Users.USERS
        );
    }
}
