/*
 * This file is generated by jOOQ.
 */
package org.dazai.booksourcing.auth.domain.db;


import org.dazai.booksourcing.auth.domain.db.tables.JwtTokens;
import org.dazai.booksourcing.auth.domain.db.tables.Users;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in DEFAULT_SCHEMA.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index JWT_TOKENS__REVOKED__IDX = Internal.createIndex(DSL.name("jwt_tokens__revoked__idx"), JwtTokens.JWT_TOKENS, new OrderField[] { JwtTokens.JWT_TOKENS.REVOKED }, false);
    public static final Index JWT_TOKENS__USER_ID__IDX = Internal.createIndex(DSL.name("jwt_tokens__user_id__idx"), JwtTokens.JWT_TOKENS, new OrderField[] { JwtTokens.JWT_TOKENS.USER_ID }, false);
    public static final Index USERS__DISABLED_USERNAME__IDX = Internal.createIndex(DSL.name("users__disabled_username__idx"), Users.USERS, new OrderField[] { Users.USERS.IS_DISABLED, Users.USERS.USERNAME }, false);
}
