/*
 * This file is generated by jOOQ.
 */
package org.dazai.booksourcing.auth.domain.db;


import org.dazai.booksourcing.auth.domain.db.tables.FlywaySchemaHistory;
import org.dazai.booksourcing.auth.domain.db.tables.JwtTokens;
import org.dazai.booksourcing.auth.domain.db.tables.UserRoles;
import org.dazai.booksourcing.auth.domain.db.tables.Users;
import org.dazai.booksourcing.auth.domain.db.tables.records.FlywaySchemaHistoryRecord;
import org.dazai.booksourcing.auth.domain.db.tables.records.JwtTokensRecord;
import org.dazai.booksourcing.auth.domain.db.tables.records.UserRolesRecord;
import org.dazai.booksourcing.auth.domain.db.tables.records.UsersRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * DEFAULT_SCHEMA.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> PK_FLYWAY_SCHEMA_HISTORY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("pk_flyway_schema_history"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<JwtTokensRecord> PK_JWT_TOKENS = Internal.createUniqueKey(JwtTokens.JWT_TOKENS, DSL.name("pk_jwt_tokens"), new TableField[] { JwtTokens.JWT_TOKENS.JWT_TOKEN }, true);
    public static final UniqueKey<UserRolesRecord> PK_USER_ROLES = Internal.createUniqueKey(UserRoles.USER_ROLES, DSL.name("pk_user_roles"), new TableField[] { UserRoles.USER_ROLES.USER_ID, UserRoles.USER_ROLES.ROLE }, true);
    public static final UniqueKey<UsersRecord> PK_USERS = Internal.createUniqueKey(Users.USERS, DSL.name("pk_users"), new TableField[] { Users.USERS.ID }, true);
}
