/*
 * This file is generated by jOOQ.
 */
package org.dazai.booksourcing.auth.domain.db.tables.records;


import org.dazai.booksourcing.auth.domain.db.tables.JwtTokens;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JwtTokensRecord extends UpdatableRecordImpl<JwtTokensRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DEFAULT_SCHEMA.jwt_tokens.jwt_token</code>.
     */
    public void setJwtToken(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.jwt_tokens.jwt_token</code>.
     */
    public String getJwtToken() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.jwt_tokens.expiration_ts</code>.
     */
    public void setExpirationTs(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.jwt_tokens.expiration_ts</code>.
     */
    public Long getExpirationTs() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.jwt_tokens.user_id</code>.
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.jwt_tokens.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.jwt_tokens.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.jwt_tokens.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.jwt_tokens.revoked</code>.
     */
    public void setRevoked(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.jwt_tokens.revoked</code>.
     */
    public Boolean getRevoked() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JwtTokensRecord
     */
    public JwtTokensRecord() {
        super(JwtTokens.JWT_TOKENS);
    }

    /**
     * Create a detached, initialised JwtTokensRecord
     */
    public JwtTokensRecord(String jwtToken, Long expirationTs, Long userId, String type, Boolean revoked) {
        super(JwtTokens.JWT_TOKENS);

        setJwtToken(jwtToken);
        setExpirationTs(expirationTs);
        setUserId(userId);
        setType(type);
        setRevoked(revoked);
        resetChangedOnNotNull();
    }
}
