name: Build and Push Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Custom Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and Push Main Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_main
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.REGISTRY_URL }}/booksourcing-main:latest,${{ secrets.REGISTRY_URL }}/booksourcing-main:${{ github.sha }}

  build-auth:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Custom Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and Push Auth Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_auth
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.REGISTRY_URL }}/booksourcing-auth:latest,${{ secrets.REGISTRY_URL }}/booksourcing-auth:${{ github.sha }}
